from sparse_gym_mujoco.envs.mujoco_env import MujocoEnv
# from gym.envs.mujoco.mujoco_env import MujocoEnv
from sparse_gym_mujoco.envs.sparse_hopper import SparseHopperEnv
from sparse_gym_mujoco.envs.sparse_halfcheetah import SparseHalfCheetahEnv
from sparse_gym_mujoco.envs.sparse_walker2d import SparseWalker2dEnv
from sparse_gym_mujoco.envs.sparse_swimmer import SparseSwimmerEnv
from sparse_gym_mujoco.envs.sparse_ant import SparseAntEnv
from sparse_gym_mujoco.envs.sparse_humanoid import SparseHumanoidEnv